### PR TITLE
Better Angels cover photos

### PR DESCRIPTION
**Pull request by pnppl**

### CODE REVIEW

**Comment by meitar** [comment]
Is there something wrong with my browser or do somevof these files have no contents? :/ I'm not seeing the "Call a friend, not the cops" text and a couple are totally transparent?

**Comment by pnppl** [comment]
My browser doesn't render them properly either. I'll try to clean them up a bit

**Comment by meitar** [comment]
I wonder if maybe our computers are showing us different things. Here's what both the SVG and the exported PNG of the `better angels cover facebook call a friend.svg` file looks like:

screen shot 2016-04-12 at apr 12 9 38 38 pm

The text doesn't seem to be what you intend it to be. When I export this SVG as a PNG, I get the same result. When you re-download the file from GitHub, does it look the same on your Inkscape?

I'm seeing similar issues of missing graphical elements in some of the other files, too. :\

**Comment by pnppl** [comment]
Here's how that file displays in my browser (Firefox 45.0.1, Linux):
screenshot_2016-04-17_09-15-14

Here's how it looks in my editor and how it looks after exporting to PNG (Inkscape, 0.91):
better angels cover facebook call a friend

**Comment by meitar** [comment]
Weeeeeeiirrrdd. I'm using the same Inkscape version but on a Mac. I found [this thread about Mac OS X not rendering SVG text](http://www.oxygenxml.com/forum/topic11426.html), and the symptoms sound similar. I'm gonna have a closer look at the SVG itself after I get some rest, since the problem very well may be the Mac OS X renderer, not the files.

**Comment by meitar** [comment]
Okay, I figured out why your SVG text is not displaying in browsers. The TL;DR: Select the text in the image and then use the "Convert to Text" command in the Text menu. (See [this SO Q&A](https://stackoverflow.com/a/19391378/4463672).)

The long story: by default, because it's *awesome*, Inkscape supports [the W3C standard for SVG 1.2](https://www.w3.org/TR/2005/WD-SVG12-20050413/), which never made it past "Working Draft" state, so most other software doesn't completely support it. Instead, there is a new version of ([SVG 2](https://www.w3.org/TR/SVG2/)) which is also currently a Working Draft but that supports a more Web-like system for text.

In SVG1.2, text can be placed on a page by using the `<flowRoot>` element and its descendants, which are not supported by any browser. So when Firefox, et. al., encounters this element, they ignore it. That's what Inkscape used, see [these lines of code](https://github.com/pnppl/better-angels/blob/master/images/better%20angels%20cover%20facebook%20call%20a%20friend.svg?short_path=2a291a7#L106-L125). By selecting the text in the Inkscape editor window, and then using the "Convert to Text" command, you're telling Inkscape, "Don't use `<flowRoot>` for this, use `<svg:text>` instead." [The `<svg:text>` element](https://www.w3.org/TR/2003/REC-SVG11-20030114/text.html#TextElement) is an SVG 1.1 compliant element, which did make it to an W3C Recommendation.

So that's the mystery for why the text isn't appearing!

I'm still not entirely sure why the spacing is totally wrong, though. Maybe if you try making this change in your source files and then committing them as `<svg:text>` elements it'll work better? Can we give that a shot?

**Comment by pnppl** [comment]
I did that and reuploaded, but they still look awful fucky in my browser. Some of them don't render at all.

**Comment by meitar** [comment]
Yeah, the "Convert to Text" was clearly not the only issue, but *all* the text is visible for me, now, including in my browsers, so I know that was part of it. Now that I can actually see the text rendered, let me have a look and see if there's some more massaging I can do to clean things up. Thanks for working through this with me!

**Comment by meitar** [comment]
Okay, so another part of the problem is that I didn't have the Lato fonts installed on my computer. Lato is thankfully a free and open source font family so I was able to [download them from here](http://www.latofonts.com/lato-free-fonts/). After I installed them, the Inkscape rendering was perfect. :)

This doesn't fix the SVG-in-browser rendering problems, which I think is also largely due to the fact that the SVG text is real text, not a path. But this is okay! Because, as you said, we're not using these SVG files as browser images, we're using them as source code that will be rasterized into PNGs for the Web anyway.

So I think this solved the problem!

Thanks so much for cleaning these up and providing the sources in beautiful, editable SVG files! This is *so* much better than requiring Adobe Illustrator!

**Comment by pnppl** [comment]
No problem! :)

**Pull request merged**
